spring:
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
---
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:6541/wine-shop-db
    driverClassName: org.postgresql.Driver
    password: postgres